5_filosofi.c
NAME
5_filosofi.c -
SYNOPSIS
#include <stdio.h>
#include <string.h>
#include <sys/types.h>
#include <sys/ipc.h>
#include <sys/sem.h>
#include <signal.h>
#include <errno.h>
#include <unistd.h>
Macros
#define DOWN (-1)
#define UP (1)
#define MYCODE 'a'
Functions
void sem_up (int ipcid, int nsem)
Dello zucchero sintattico per fare la UP.
void sem_down (int ipcid, int nsem)
Dello zucchero sintattico per fare la DOWN.
void sem_set (int ipcid, int nsem, int initial)
Dello zucchero sintattico per impostare il valore di un semaforo.
void prendi (int ipcid, int nSem)
Funzione che simula quando il filosofo prende una bacchetta.
void posa (int ipcid, int nSem)
Funzione che simula quando il filosofo posa una bacchetta.
void filosofo (int ipcid, int i_filos)
Codice di prova per i filosofi.
int main ()
Macro Definition Documentation
#define DOWN (-1)
Definition at line 21 of file 5_filosofi.c.
Referenced by sem_up().
#define MYCODE 'a'
Definition at line 23 of file 5_filosofi.c.
Referenced by main().
#define UP (1)
Definition at line 22 of file 5_filosofi.c.
Referenced by sem_up().
Function Documentation
void filosofo (int ipcid, int i_filos)
Codice di prova per i filosofi.
Parameters:
ipcid Riceve il numero dell`oggetto IPC
Il filosofo pensa e mangia facendo up and down sul semaforo rappresentante le posate. Filosofo Pensa
Filosofo Vuole mangiare
Definition at line 138 of file 5_filosofi.c.
References posa(), and prendi().
Referenced by main().
int main ()
inizializza i semafori a 1
ciclo per la creazione dei 5 figli filosofi
Aggiorno contatore dei filosofi creati. Ogni filosofo avrà il giusto numero.
Definition at line 156 of file 5_filosofi.c.
References filosofo(), MYCODE, and sem_set().
void posa (int ipcid, int nSem)
Funzione che simula quando il filosofo posa una bacchetta.
Definition at line 116 of file 5_filosofi.c.
References sem_up().
Referenced by filosofo().
void prendi (int ipcid, int nSem)
Funzione che simula quando il filosofo prende una bacchetta.
Definition at line 100 of file 5_filosofi.c.
References sem_down().
Referenced by filosofo().
void sem_down (int ipcid, int nsem)
Dello zucchero sintattico per fare la DOWN.
Parameters:
ipcid Riceve il numero dell`oggetto IPC
nsem Il semaforo su cui fare DOWN
Questa chiamata maschera i dettagli implementativi sul buffer delle operazioni IPC
Definition at line 65 of file 5_filosofi.c.
Referenced by prendi(), and sem_up().
void sem_set (int ipcid, int nsem, int initial)
Dello zucchero sintattico per impostare il valore di un semaforo.
Parameters:
ipcid Riceve il numero dell`oggetto IPC
nsem Il semaforo da impostare
initial Il valore iniziale del semaforo
Questa chiamata maschera i dettagli implementativi sul buffer delle operazioni IPC
Definition at line 87 of file 5_filosofi.c.
Referenced by main().
void sem_up (int ipcid, int nsem)
Dello zucchero sintattico per fare la UP.
Parameters:
ipcid Riceve il numero dell`oggetto IPC
nsem Il semaforo su cui fare UP
Questa chiamata maschera i dettagli implementativi sul buffer delle operazioni IPC
Definition at line 46 of file 5_filosofi.c.
References DOWN, sem_down(), and UP.
Referenced by posa().
Author
Generated automatically by Doxygen for My Project from the source code.