semthread.c
NAME
semthread.c -
SYNOPSIS
#include <stdio.h>
#include <unistd.h>
#include <semaphore.h>
#include <pthread.h>
Functions
void * thread1 (void *arg)
semafori
void * thread2 (void *arg)
Codice del thread2 Il thread fa Pong e fa UP sul semaforo dell`altro thread.
int main ()
Variables
static sem_t s1
static sem_t s2
Function Documentation
int main ()
Definition at line 52 of file semthread.c.
References s1, s2, thread1(), and thread2().
void* thread1 (void * arg)
semafori Codice del thread1 Il thread fa Ping e fa UP sul semaforo dell`altro thread
Definition at line 23 of file semthread.c.
References s1, and s2.
Referenced by main().
void* thread2 (void * arg)
Codice del thread2 Il thread fa Pong e fa UP sul semaforo dell`altro thread.
Definition at line 39 of file semthread.c.
References s1, and s2.
Referenced by main().
Variable Documentation
sem_t s1 [static]
Definition at line 17 of file semthread.c.
Referenced by main(), thread1(), and thread2().
sem_t s2 [static]
Definition at line 17 of file semthread.c.
Referenced by main(), thread1(), and thread2().
Author
Generated automatically by Doxygen for My Project from the source code.