sem.c
NAME
sem.c -
SYNOPSIS
#include <stdio.h>
#include <string.h>
#include <sys/types.h>
#include <sys/ipc.h>
#include <sys/sem.h>
#include <signal.h>
#include <errno.h>
#include <unistd.h>
Macros
#define DOWN (-1)
#define UP (1)
#define MYCODE 'a'
Functions
void sem_up (int ipcid, int nsem)
Dello zucchero sintattico per fare la UP.
void sem_down (int ipcid, int nsem)
Dello zucchero sintattico per fare la DOWN.
void sem_set (int ipcid, int nsem, int initial)
Dello zucchero sintattico per impostare il valore di un semaforo.
void padre (int ipcid)
Codice di prova per il padre.
void figlio (int ipcid)
Codice di prova per il figlio.
int main ()
Macro Definition Documentation
#define DOWN (-1)
Definition at line 21 of file sem.c.
Referenced by sem_up().
#define MYCODE 'a'
Definition at line 23 of file sem.c.
Referenced by main().
#define UP (1)
Definition at line 22 of file sem.c.
Referenced by sem_up().
Function Documentation
void figlio (int ipcid)
Codice di prova per il figlio.
Parameters:
ipcid Riceve il numero dell`oggetto IPC
Il figlio fa Pong e fa UP sul semaforo del padre
Definition at line 121 of file sem.c.
References sem_down(), and sem_up().
Referenced by main().
int main ()
inizializza il semaforo 0 a 1
inizializza il semaforo 1 a 0
Definition at line 132 of file sem.c.
References figlio(), MYCODE, padre(), and sem_set().
void padre (int ipcid)
Codice di prova per il padre.
Parameters:
ipcid Riceve il numero dell`oggetto IPC
Il Padre fa Ping e fa UP sul semaforo del figlio
Definition at line 104 of file sem.c.
References sem_down(), and sem_up().
Referenced by main().
void sem_down (int ipcid, int nsem)
Dello zucchero sintattico per fare la DOWN.
Parameters:
ipcid Riceve il numero dell`oggetto IPC
nsem Il semaforo su cui fare DOWN
Questa chiamata maschera i dettagli implementativi sul buffer delle operazioni IPC
Definition at line 66 of file sem.c.
Referenced by figlio(), padre(), and sem_up().
void sem_set (int ipcid, int nsem, int initial)
Dello zucchero sintattico per impostare il valore di un semaforo.
Parameters:
ipcid Riceve il numero dell`oggetto IPC
nsem Il semaforo da impostare
initial Il valore iniziale del semaforo
Questa chiamata maschera i dettagli implementativi sul buffer delle operazioni IPC
Definition at line 87 of file sem.c.
Referenced by main().
void sem_up (int ipcid, int nsem)
Dello zucchero sintattico per fare la UP.
Parameters:
ipcid Riceve il numero dell`oggetto IPC
nsem Il semaforo su cui fare UP
Questa chiamata maschera i dettagli implementativi sul buffer delle operazioni IPC
Definition at line 47 of file sem.c.
References DOWN, sem_down(), and UP.
Referenced by figlio(), and padre().
Author
Generated automatically by Doxygen for My Project from the source code.