.TH "pipe-mod.c" 3 "Sun Jun 26 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pipe-mod.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBUFFER_SIZE\fP   50"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BUFFER_SIZE   50"

.PP
Definition at line 14 of file pipe\-mod\&.c\&.
.PP
Referenced by main()\&.
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Definition at line 16 of file pipe\-mod\&.c\&.
.PP
References BUFFER_SIZE\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
