.TH "shmem.c" 3 "Sun Jun 26 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shmem.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <sys/ipc\&.h>\fP
.br
\fC#include <sys/shm\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSIZE\fP   10"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SIZE   10"

.PP
Definition at line 21 of file shmem\&.c\&.
.PP
Referenced by main()\&.
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Definition at line 23 of file shmem\&.c\&.
.PP
References SIZE\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
