.TH "exCreazioneThread.c" 3 "Sun Jun 26 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
exCreazioneThread.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <pthread\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBmy_thread\fP (void *arg)"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Definition at line 27 of file exCreazioneThread\&.c\&.
.PP
References my_thread()\&.
.SS "void* my_thread (void * arg)"

.PP
Definition at line 16 of file exCreazioneThread\&.c\&.
.PP
Referenced by main()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
